### PR TITLE
[PHP] Change default php image to use PHP 7.0

### PR DESCRIPTION
**Pull request by andrerom**
PHP 7.0 is now GA.

### CODE REVIEW

**Comment by andrerom** [comment]
@vidarl could you ping me on when you'll have time to check how this works?
Mainly you should check image-size and memory use, latter should be lower but just to avoid any surprises when doing this on devdemo and democloud. 

We should also try to benchmark *(ab, jmeter, api)* this in preparations for a blog post, but I'll try to find time to do that at home later next week /cc @bdunogier @rolandbenedetti

**Comment by vidarl** [comment]
I'll have a look at it now

**Comment by vidarl** [comment]
@andrerom : Can you review my small changes then, and I'll merge

**Comment by andrerom** [comment]
Where do you need mysql client in php container?

**Comment by vidarl** [comment]
I use that to check in scripts if mysql is up and running yet.
For instance in dockerfiles/ezphp/prepare_distribution_volume.sh ( before importing DB )
and create_distro_containers.sh before running installer

**Comment by andrerom** [comment]
ok,but then guess you'll soon need to think about a more generic way to do this soon when we add postgres.

+1

**Comment by vidarl** [comment]
Yes, I guess so too....

**Pull request merged**
