### PR TITLE
Solr

### PR DESCRIPTION
**Pull request by vidarl**
Solr is now configured and working with Petar's latest changes.
However, things are still subject to change according to Petar.

This PR currently patch the solr bundle in order to get it running. ( Alternative would be to create it's own bundle containing the service.yml settings ). But I guess there will eventually be a different/better way of setting this up anyway so didn't spend more time on doing it cleanly.

Since solr things are still subject to change, I propose we do not merge this PR before things has been settled down.

### CODE REVIEW

**Comment by vidarl** [comment]
@andrerom : Please have a look

**Comment by andrerom** [comment]
+ (however lets indeed wait until it has settled, several PR's in review now)

**Comment by pspanja** [comment]
With https://github.com/ezsystems/ezpublish-kernel/pull/1181 now merged, things should stay stable until  semantic configuration for Search Engines is implemented (see https://jira.ez.no/browse/EZP-23471).
Remaining refactoring PRs will not introduce any changes in this regard.

Only required change here is replacing `legacy_solr` with `solr` at https://github.com/ezsystems/ezpublish-docker/pull/28/files#diff-024de0f2b7a4fbafccbadcd7f4cd09c3R3.

**Comment by andrerom** [comment]
@pspanja How can we avoid having to patch ezpublish-kernel?

**Comment by pspanja** [comment]
At this point only by creating a separate bundle and loading configuration with alias override from there.

**Comment by andrerom** [comment]
@vidarl I think this should be ready now, @pspanja might point you to how to configure this.

**Comment by andrerom** [comment]
Closing, will do probably use some stuff here but do it differently as master has now changed a lot.

**Pull request closed without merging**
