### PR TITLE
Aws volumesize

### PR DESCRIPTION
**Pull request by vidarl**
Added support for setting volume size.
As the  composer cache grows, the default size ain't big enough....

### CODE REVIEW

**Comment by vidarl** [comment]
@andrerom : Ready for review

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
define "grows" ?
As in it does not delete old cache items?

there might be a setting to limit the cache btw

**Comment by vidarl** [comment]
Yeah. The composer cache here is now 2.6Gb
And I have frankly never seen the composer cache shrink automatically

**Comment by andrerom** [comment]
Looks to be happening only around every 50 times it is used: https://github.com/composer/composer/blob/master/src/Composer/Cache.php#L151

but in your case you share the cache from host right? or have you reached this problem on AWS also? (which I assume only execute composer once during install?)

**Comment by vidarl** [comment]
This is on AWS, yes.
However, I see that the a old composer cache is rsynced ( and thereby overwrite the composer cache from previous execution ) every time.

So, I guess the fix is to avoid the composer cache from being rsynced. The downside of that, is that once you initialize a new coreOS ( on AWS or wherever ), the composer cache will not be warm unless you copy a composer cache over to the VM manually...

I'll update this PR to avoid the rsync of composer cache

**Comment by vidarl** [comment]
hmmm.. I will not update the rsync to ignore the composer cache..

The problem is that when you do a "vagrant provision" on virtualbox, an rsync is *not* taking place.
However, the aws provider *will* do a rsync when doing "vagrant provision".
The virtualbox's behavior is the correct one IMO.
So, the correct fix is to use the "debug.disable_rsync" setting in vagrant.yml when using AWS provider

However, I still think this PR is a good idea ( to make it possible to configure the size of the AWS instance )

**Comment by andrerom** [comment]
ok, +1

**Pull request merged**
