### PR TITLE
Switched to using official nginx image

### PR DESCRIPTION
**Pull request by vidarl**
With this PR we are getting rid of  our custom nginx image

Dependent on this other PR
- https://github.com/ezsystems/ezplatform/pull/81

### CODE REVIEW

**Comment by vidarl** [comment]
@andrerom : please have a look

**Comment by vidarl** [comment]
If nginx do not accept the PR,  an alternative solution would be to  generate the config in an temporary container ( managed by docker-compose_ezpinstall.sh ) and then put the generated config in a volume container which will be used by docker-compose.yml

**Comment by vidarl** [comment]
@andrerom : Ready for review, ready to be merged as soon as https://github.com/ezsystems/ezplatform/pull/81 is merged too

**Comment by vidarl** [comment]
hmm.. will https://github.com/ezsystems/ezplatform/pull/81 be merged to 5.4? if not, I have to create a separate docker-compose.yml for ezp 5.4

**Comment by andrerom** [comment]
> 5.4

yes we can do that

**Pull request closed without merging**
