### PR TITLE
Now builds both php5 and php7 image as eZ Publish 5.4 still requires php5

### PR DESCRIPTION
**Pull request by vidarl**
After switching to php7, we still need to build php5 image in order to use eZ Publish 5.4

### CODE REVIEW

**Comment by vidarl** [comment]
@andrerom : Ready for review

**Comment by vidarl** [comment]
Update : not ready for review after all... Needs some changes in create_distro_container.sh too

**Comment by vidarl** [comment]
@andrerom : Ready for review

**Comment by andrerom** [comment]
+1

**Pull request merged**
